"""add parsed_text and processing_status to documents

Revision ID: a8b4e8b23112
Revises: 820dbd7c5b3b
Create Date: 2026-09-02 13:57:07.860652

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8b4e8b23112'
down_revision: Union[str, None] = '820dbd7c5b3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('parsed_text', sa.Text(), nullable=True))
    op.add_column('documents', sa.Column('processing_status', sa.String(length=20), server_default='uploaded', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'processing_status')
    op.drop_column('documents', 'parsed_text')
    # ### end Alembic commands ###
